### ISSUE TITLE
Revert reason string not working in Ganache desktop app

### ISSUE THREAD

**Issue by derdrdirk** [rkalis/truffle-assertions#12]
I have a function in my Smart Contract that only shall be executed by the Smart Contract owner:
```
 function test(address _from, address _to, uint256 _value) public returns (bool success) {
    require(msg.sender == contract_owner);
  }

```

In my test I try to use your `truffleAssert.reverts` function:
 ```
it('should not allow transfers between token holders', async () => {
    const cuatre = await Cuatre.deployed()
    await truffleAssert.reverts(cuatre.transferFrom(accountOne, accountTwo, amount, { from: accountOne }), "only owner")
 })

```

But running the test via `truffle test` fails with the following output:

>  1) Contract: Test Cuatre smart contract
>        should not allow transfers between token holders:
>      AssertionError: Expected to fail with revert, but failed with: Error: VM Exception while processing transaction: revert
>       at fails (node_modules/truffle-assertions/index.js:139:13)
>       at process._tickCallback (internal/process/next_tick.js:68:7)

Am I doing something wrong?

**Comment by rkalis** [comment]
Hi @Knowledge91!

It appears that Truffle is not outputting the revert reason. This is a very new feature and only works with the Truffle v5-beta and higher, as well as the latest version of ganache-cli. 

If you're using an earlier version of Truffle, you can choose to update to the latest beta version of Truffle.
```
npm install -g truffle@beta
```

If you'd rather stay on Truffle v4 for now, you can't use the revert reason inside your unit tests. You can still use the `truffleAssert.reverts()` assertion, but without the revert reason:

```
await truffleAssert.reverts(cuatre.transferFrom(accountOne, accountTwo, amount, { from: accountOne }))
```

If you are already updated to the latest Truffle beta version and the latest version of ganache-cli, and it's still not working, let me know.

**Comment by derdrdirk** [comment]
thank for the quick reply @rkalis 

the code works fine without the reasoning but still yields the same error in the truffle beta version.
I am pretty fine without putting a reason, so you can close.

FYI: 
The exact version I am using is `Truffle v5.0.0-beta.2` with Ganache 1.2.2. I am using the Desktop application (not ganache-cli).

**Comment by rkalis** [comment]
Hi @Knowledge91 

Unfortunately, the Ganache desktop app doesn't have support for revert reason strings yet, so to test for the reason strings you have to wait a bit longer for the Truffle team to release a new version of Ganache, or use ganache-cli instead.
