### ISSUE TITLE
Question : also possible to check the index from an event?

### ISSUE THREAD

**Issue by StefH** [rkalis/truffle-assertions#14]
What I want to to check that `Event-1` is submitted before `Event-2`.

``` js
truffleAssert.eventEmitted(result, 'Event-1', (ev) => {
    return ev.index == 0;
});

truffleAssert.eventEmitted(result, 'Event-2', (ev) => {
    return ev.index == 1;
});
```

Is this possible?

**Comment by rkalis** [comment]
Hi @StefH 

This is currently not possible using the library, but it is something that could be implemented. I'll think about how this could be done.

**Comment by DefiCake** [comment]
This would be a nice addition in case a transaction emits the same event multiple times.

**Comment by rkalis** [comment]
Since Truffle is being sunset, I don't plan to add new features, so I'm closing this issue.
