### ISSUE TITLE
Indentation of getPrettyEmittedEventsString doesn't always make sense

### ISSUE THREAD

**Issue by ItsNickBarry** [rkalis/truffle-assertions#17]
When adding indentation, `getPrettyEmittedEventsString` assumes that the test is nested only one level deep, within the `contract` block.  When using `Mocha.describe`, however, tests may be deeply nested, and therefore require more indentation.

Ideally the indentation given by `getPrettyEmittedEventsString` would match that of the test itself.  If that isn't possible, in my opinion, it might be better not to indent at all.

**Comment by rkalis** [comment]
It doesn't appear to be possible to infer indentation level from Mocha, and I guess we should be compatible with different test runners. I don't have a strong preference for the indentation of the message, so I'll leave this open for now and allow other people to suggest something as well, or react to this comment.

React to this comment with :smile: for no indentation, or with :tada: for 4 space (current) indentation for getPrettyEmittedEventsString / prettyPrintEmittedEvents, or suggest another solution below.

**Comment by ItsNickBarry** [comment]
Something to consider: any `console.log` calls used for debugging will lack indentation entirely.  Perhaps `getPrettyEmittedEventsString` should be consistent with `console.log`.

**Comment by rkalis** [comment]
Yeah I guess it makes sense to do it like that. If people want to add indentation, they'd be able to prepend the string with the needed amount of spaces and running a replaceAll replacing all newlines with newline + spaces. Could you raise a PR removing the indentation?

**Comment by ItsNickBarry** [comment]
Actually, I made a mistake.  I wasn't looking at `getPrettyEmittedEventsString` at all, but instead at the logs which print as the tests are running, produced [here](https://github.com/trufflesuite/truffle/blob/e913be03c564cd967d58a67ddc16360188db3ead/packages/truffle-core/lib/testing/testrunner.js#L161).

Still, I think that when called directly, `getPrettyEmittedEventsString` should not have indentation.

The logs from `getPrettyEmittedEventsString` which print along with the errors would actually be fine with a single level of indentation; however, the indentation of the error messages is five spaces at the top level, plus two per nested block, with the default configuration.

```
  1) Contract: TestContract
       #testFunction
         emits event:
     AssertionError: Event of type TestEvent was not emitted
    Events emitted in tx 0x7ec1c48be2ec171fd8ff945115bf23fec6f3ebc38c7b2cf63db4da483101bd20:
    ...
```

I'm not sure whether it's Truffle or Mocha which specifies the five-space indentation.  If it's the former, I think it would be best to match the indentation.  However, if it's the latter, I think it would be inappropriate to do the same here, so I'll remove the indentation entirely.
