### ISSUE TITLE
truffleAssert.reverts not working but error msg is displayed instead

### ISSUE THREAD

**Issue by ratio91** [rkalis/truffle-assertions#23]
**Describe the bug**
When I run a test using truffleAssert.reverts(), I get the following error:

> Error: Returned error: VM Exception while processing transaction: revert no more new tickets available -- Reason given: no more new tickets available.

Which is great, because it means the modifier works as expected. 
However the test fails, and this should not happen - as this is the exact point I want to prove.

**Example test code**

```js
it('It should NOT be possible to do buy new tickets if supply has run out', async () => { 
  let t = await instance.buyTicket({ value: 1e+18, from: attendee2 });
  truffleAssert.reverts(t, "no more new tickets available");
});
```
also tried without reason string -> same result

**Expected behavior**
test should be successful as revert is thrown correctly.

**Environment Information**
"truffle": "^5.0.3",
"truffle-assertions": "^0.8.0"

thank you!

PS: Event testing works really fine and helped me a lot, thanks for the great work!

**Comment by rkalis** [comment]
Hi @ratio91, thanks for the nice words, and for opening the issue.

So the way `reverts()` works, is that it takes the async function (or the promise) and asserts that it will revert.

What you're doing in your example, however, is awaiting the result of the function and then passing this result into the revert function. In this case, the function already reverts before the `reverts()` function can do the assertion.

You should change your code to the following:

```js
it('It should NOT be possible to do buy new tickets if supply has run out', async () => { 
  await truffleAssert.reverts(
    instance.buyTicket({ value: 1e+18, from: attendee2 }), 
    "no more new tickets available"
  );
});
```

This should work. Good luck with your smart contract development!

**Comment by ratio91** [comment]
Thanks for the fast reply, works like a charm now! 
you can close it I guess ;-)

**Comment by rkalis** [comment]
Perfect :)
