### ISSUE TITLE
Checking event spawned by fallback function

### ISSUE THREAD

**Issue by hlb8122** [rkalis/truffle-assertions#26]
Relayer:
```solidity
    function relay(address payable recipient, uint amount) public {
        require(amount < address(this).balance, "insufficient funds");
        recipient.transfer(amount);
    }
```

EthWallet:
```solidity
    function() external payable {
        // generate an event when receiving Eth
        require(msg.value > 0, "zero deposit");
        emit DepositEvent(msg.sender, msg.value);
    }
```

```javascript
    return relay_instance.relay(EthWallet.address, value_out).then(function (result) {
        truffleAssert.prettyPrintEmittedEvents(result);
        //...
```
There are no events printed, even though (if the test fails) it announces that the event was emitted. I imagine this is because of the fact that the event isn't directly emitted by the Relayer contract.

What is the work around here?

**Comment by hlb8122** [comment]
I've tried the https://github.com/zulhfreelancer/truffle-events package, however I could not get it to work.

I imagine this is because the event is not emitted by a nested contract call or I've set it up wrong.

**Comment by rkalis** [comment]
This is an interesting case, thanks for opening the issue @hlb8122.

I will see if I can reproduce this over the weekend.

**Comment by hlb8122** [comment]
Any luck?

**Comment by rkalis** [comment]
Hey @hlb8122 sorry for dropping the ball on this one, I completely forgot to get into this issue. I haven't tested this yet, but can you try this:

```js
return relay_instance.relay(EthWallet.address, value_out).then(function (result) {
    const ethWalletResult = truffleAssert.createTransactionResult(ethwallet_instance, result.tx);
    truffleAssert.prettyPrintEmittedEvents(ethWalletResult);
    // ...
}
```

**Comment by rkalis** [comment]
@hlb8122 were you able to use the solution I presented?

**Comment by naiba** [comment]
@rkalis It works for me

**Comment by hlb8122** [comment]
@rkalis  sorry for slow reply, works for me too :)
