### ISSUE TITLE
Capturing multiple events

### ISSUE THREAD

**Issue by kallolborah** [rkalis/truffle-assertions#35]
@rkalis thanks for the great work here.

I am using truffle-assertions in my project but have a hard time figuring out how to extract two separate events from two calls to an oracle that are made one after the other. I am also not really a javascript programmer, so do excuse any mistakes here but this is what I am doing :

```js
contract("sample", async (accounts) => {
  it("do something", async () => {
    let firstCallbackToOracle = await getFirstEvent(oracle.LogResult({fromBlock:'latest'}));
    await truffleAssert.createTransactionResult(oracle, firstCallbackToOracle.transactionHash);
    let secondCallbackToOracle = await getFirstEvent(oracle.LogResult({fromBlock:'latest'}));
    await truffleAssert.createTransactionResult(oracle, secondCallbackToOracle.transactionHash);
  });

  const getFirstEvent = (_event) => {
    return new Promise((resolve, reject) => {
      _event.once('data', resolve).once('error', reject)
    });
  }
});
```
What I get from such a test in truffle (v5.1.53) is -
 Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. 

The oracle calls back and I do not see any issue with why a timeout should occur, and I also see test cases with single callbacks work well, and this leads to me think I am doing something wrong with how multiple callbacks have to be listened to and confirmed.

Your advice will be appreciated.

**Comment by rkalis** [comment]
Hey, it's difficult to debug without knowing more. 

But I think this is because you're doing `await getFirstEvent(oracle.LogResult({fromBlock:'latest'}));` but you're never calling any contract functions that can trigger that event after you're listening for it.

If you want to look for events in the *past* (because the oracle event should already have been emitted at that point, you need to change `fromBlock: 'latest'` to something else, since `'latest'` means it only checks events in the future (not the past).

**Comment by kallolborah** [comment]
Thanks @rkalis, please see my notes below
> 
> But I think this is because you're doing `await getFirstEvent(oracle.LogResult({fromBlock:'latest'}));` but you're never calling any contract functions that can trigger that event after you're listening for it.
- You mention 'calling any contract functions that can trigger that event' : which event are you referring to ? I am not calling any contract functions because the oracle itself calls back the contract function after listening to the event.
> 
> If you want to look for events in the _past_ (because the oracle event should already have been emitted at that point, you need to change `fromBlock: 'latest'` to something else, since `'latest'` means it only checks events in the future (not the past).
- Just before the first callback, I call the oracle, so I am listening for only callbacks in the future. I tried using the 'from' also but I am still getting a time out.

**Comment by kallolborah** [comment]
@rkalis i also want to check an alternative with you. Instead of waiting for a callback from oraclize, can not we instead use truffleAssert.eventEmitted(...) to catch the event emitted after oraclize calls back ?

I want to do something like this :
var event_param = await truffleAssert.eventEmitted(tx_receipt, event_name, (ev)=>{ 
                               check (ev.event_param);
                               return (ev.event_param);
});

Is something like the above possible ? 
Thanks !
