### ISSUE TITLE
Assert nested/internal events

### ISSUE THREAD

**Issue by kivanov82** [rkalis/truffle-assertions#6]
First, thank you for the great package!

I'm trying to assert an event from internal/nested transaction but no success so far.
Providing original tx object results in "AssertionError: Event of type XYZ was not emitted"

Tried also truffleAssert.createTransactionResult() providing instance of child contract and a hash of 'original' tx but no luck

Truffle 5.0, web3 1.0

PS. Truffle sees such an event and displays it in Events emitted during test:

**Comment by rkalis** [comment]
Hi @kivanov82 

Thank you for opening this bug report. Do you have some example code where this happens so that I can look at what is happening?

**Comment by kivanov82** [comment]
The case is just a simple nested call to another contract which emits an event.
Like "tx" -> contract "A" -> call contract  "B" which emits event "X". 
Something like this: https://ethereum.stackexchange.com/questions/2942/how-do-you-get-events-from-a-function-in-another-contract

Using just 
truffleAssert.eventEmitted(tx, 'X', (ev) ) will complain about missing event.

I actually made it work like this:
let nestedEventValues = (await truffleAssert.createTransactionResult(B, tx.tx)).logs[0].returnValues;
As you see I used an instance of 'child' contract and a hash of 'main' tx.

Would be great having it as a general assertion function.

**Comment by rkalis** [comment]
Good to hear that you found a workaround for now.

I will look at what the best way is to handle this in a more straightforward way in the future.

**Comment by ejwessel** [comment]
FWIW as an extension of @kivanov82 's answer
```
let newTx = await truffleAssert.createTransactionResult(B, tx.tx);
truffleAssert.eventEmitted(newTx, eventType[, filter][, message])
```

**Comment by leonprou** [comment]
Nice! it's also easy to add an inner function to your test class. following your example:

```
contract ('A', () => {
  let B

  const eventEmitted = async (result, ...args) => {
    const resultsOfB = await truffleAssert.createTransactionResult(B, result.tx)
    truffleAssert.eventEmitted(resultsOfB, ...args)
  }
}
```

I had my own struggle with that problem but on the `web3` side, described a possible solution here: https://ethereum.stackexchange.com/questions/70565/reading-events-of-the-inner-solidity-contract-with-web3/70566#70566. 
But failed to make it work with truffle, might require more tinkering.

**Comment by PaulRBerg** [comment]
I also encountered this issue. @rkalis I guess you could use the logic from this [SE answer](https://ethereum.stackexchange.com/a/61967/24693) to make this feature native to truffle-assertions?

Copy-pasting for reference:

```
const keccak256 = web3.utils.keccak256;
...
const tx = await instance.someFunction(();
let event = tx.receipt.logs.some(l => { return l.topics[0] == '0x' + keccak256("Stored()") });
assert.ok(event, "Stored event not emitted");
```

Something like:

```
truffleAssert.nestedEventEmitted(result, "EventName");
```

## Update
It seems the snippet above doesn't work with the latest version of truffle (5.0.30).

**Comment by rkalis** [comment]
@PaulRBerg this is definitely one of the more important issues open right now. I've discussed some ways to improve this flow in #1. One thing I'm wondering if the new Truffle decoder library (truffle-codec?) will be able to decode events that are included in TransactionReceipts. This would make the whole process a bit easier as this would allow me to go from a TransactionReceipt-type log (encoded events) to a TransactionResult-type log (decoded events and event args). 

@gnidan given a transaction receipt and a contract definition / abi, will I be able to get a decoded log for that receipt using the new decoder library?

**Comment by bivalent** [comment]
Hey all, curious if this was implemented yet, seeing the merged PR from @yondonfu has me curious. Currently trying to use this libary to test smartcontract/chainlink fufillments (https://github.com/smartcontractkit/chainlink/blob/develop/evm/v0.5/contracts/Oracle.sol#L119) but the events are all nested and so do not get currently captured. Amazing library and I'm very lucky that you all have been working on it!

**Comment by rkalis** [comment]
Since Truffle is being sunset, I don't plan to add new features, so I'm closing this issue.
