### ISSUE TITLE
truffleAssert.fails catches non-failure exception

### ISSUE THREAD

**Issue by zanawar** [rkalis/truffle-assertions#7]
**Describe the bug**
Run the example code:
```await truffleAssert.fails(contractInstance.methodThatShouldFail());```

**Expected behavior**
An assertion/exception to be thrown.

**Issue Location**
https://github.com/rkalis/truffle-assertions/blob/62cd432c3b496daf478ba8bb6b5aefbd9e473263/index.js#L127

Problem exists with line 127.

https://github.com/rkalis/truffle-assertions/blob/62cd432c3b496daf478ba8bb6b5aefbd9e473263/index.js#L124-L133
The assertion error is thrown within the try/catch block so it is immediately caught. Since ```errorType``` wasn't defined, the assertion is ignored and not re-thrown.

**Comment by zanawar** [comment]
Created a fix based on upcoming 1.0 branch with this PR: https://github.com/rkalis/truffle-assertions/pull/8

**Comment by rkalis** [comment]
Hi @zanawar, thanks for finding this bug, and thank you for fully debugging and fixing it as well!
